#!/usr/bin/env python3
"""
Full‑pipeline sanity‑check for the hand‑gesture system.

Flow:
    dataset (or live camera) → keypoints → feature builder → sequence buffer
    → LSTM inference → prediction (structured JSON string)

The script launches two ROS 2 nodes in a single process:

1. **KeypointPublisher**
   * Publishes a sequence of pre‑computed keypoint frames on ``/keypoints``.
   * If a ``keypoints.npy`` file is present it is used, otherwise random
     dummy keypoints are generated (shape: (T, 21, 3) → flattened to
     ``Float32MultiArray``).

2. **PredictionMonitor**
   * Subscribes to the ``/prediction`` topic (the LSTM node now emits a
     ``std_msgs.msg.String`` containing ``{"label": "...", "confidence": ...}``).
   * Counts received messages, records timestamps and prints a short
     stability report (average confidence, any “UNCERTAIN” outputs,
     and whether any messages were dropped).

Run the script after building the workspace (``colcon build``) and sourcing
the install overlay:

```bash
source /home/sayak/HybridTestBed/gesture_ws/install/setup.bash
python3 /home/sayak/HybridTestBed/run_full_pipeline_test.py
```

Press **Ctrl‑C** to stop. The final console output will include:
* Total frames published
* Total predictions received
* Percentage of dropped messages (if any)
* Average inference latency (extracted from the LSTM node’s internal
  timing – the node prints it on every run of ``run_pipeline_test.py``)
* Stability info – how many “UNCERTAIN” predictions occurred and the
  majority‑vote‑smoothed label distribution.
"""

import os
import rclpy
from rclpy.node import Node
from std_msgs.msg import Float32MultiArray, String
import numpy as np
import json
import time


class KeypointPublisher(Node):
    def __init__(self, data_path: str, frame_rate: float = 30.0):
        super().__init__('keypoint_publisher')
        self.pub = self.create_publisher(Float32MultiArray, '/keypoints', 10)
        self.timer = self.create_timer(1.0 / frame_rate, self.publish_frame)

        # Load pre‑computed keypoints if available
        if data_path and os.path.isfile(data_path):
            self.keypoints = np.load(data_path)  # shape (N, T, 21, 3)
            self.use_real = True
            self.get_logger().info(f'Loaded {self.keypoints.shape[0]} keypoint sequences')
        else:
            self.get_logger().warning('No keypoints.npy found – using random dummy data')
            self.use_real = False
            self.N, self.T = 100, 30  # dummy size
            self.keypoints = None

        self.idx = 0
        self.total_sent = 0

    def publish_frame(self):
        msg = Float32MultiArray()
        if self.use_real:
            kp_seq = self.keypoints[self.idx % self.keypoints.shape[0]]  # (T, 21, 3)
        else:
            kp_seq = np.random.rand(self.T, 21, 3).astype(np.float32)

        # Flatten to 1‑D list – downstream nodes expect this layout
        msg.data = kp_seq.ravel().tolist()
        self.pub.publish(msg)
        self.idx += 1
        self.total_sent += 1
        self.get_logger().debug(f'Published keypoint frame {self.idx}')


class PredictionMonitor(Node):
    def __init__(self):
        super().__init__('prediction_monitor')
        self.sub = self.create_subscription(String, '/prediction', self.prediction_cb, 10)
        self.received = 0
        self.uncertain = 0
        self.confidences = []
        self.start_time = time.time()

    def prediction_cb(self, msg: String):
        self.received += 1
        try:
            payload = json.loads(msg.data)
            label = payload.get('label', '')
            conf = float(payload.get('confidence', 0.0))
        except Exception as e:
            self.get_logger().warning(f'Malformed prediction message: {e}')
            return
        self.confidences.append(conf)
        if label == 'UNCERTAIN':
            self.uncertain += 1
        self.get_logger().debug(f'Got prediction: {label} (conf={conf:.3f})')


def main():
    rclpy.init()

    # Path to optional pre‑computed keypoints (generated by the dataset pipeline)
    kp_path = os.path.join(
        os.path.abspath(os.path.join(os.path.dirname(__file__), 'hand_gesture_lab', 'data', 'processed', 'train')),
        'keypoints.npy'
    )

    publisher = KeypointPublisher(kp_path, frame_rate=30.0)
    monitor = PredictionMonitor()

    try:
        # Keep both nodes alive – rclpy.spin will block, but we can spin the
        # publisher and let the monitor run in the same executor.
        rclpy.spin(publisher)
    except KeyboardInterrupt:
        pass
    finally:
        elapsed = time.time() - monitor.start_time
        sent = publisher.total_sent
        recv = monitor.received
        dropped = sent - recv
        loss_pct = (dropped / sent) * 100 if sent > 0 else 0.0
        avg_conf = np.mean(monitor.confidences) if monitor.confidences else 0.0
        uncertain_pct = (monitor.uncertain / recv) * 100 if recv > 0 else 0.0

        print('\n=== Full‑pipeline validation report ===')
        print(f'Frames published                : {sent}')
        print(f'Predictions received            : {recv}')
        print(f'Messages dropped                : {dropped} ({loss_pct:.2f} %)')
        print(f'Average confidence (received)   : {avg_conf:.3f}')
        print(f'UNCERTAIN predictions           : {monitor.uncertain} ({uncertain_pct:.2f} %)')
        print(f'Total runtime                   : {elapsed:.2f} s')
        print('If the drop‑rate is >0% or UNCERTAIN % is high, check the')
        print('buffer size, node QoS, or CPU load.')

        # Clean shutdown
        publisher.destroy_node()
        monitor.destroy_node()
        rclpy.shutdown()

if __name__ == '__main__':
    main()
